### PR TITLE
Complete homepage

### PR DESCRIPTION
**Pull request by rquey**
- Added details on FEPX's capabilities, with bold letters to emphasize the main points
- Rolled back title as per earlier description
- Rolled back formatting of "Contents" and "Current developers".  That's maybe only a personal judgment, but I don"t think it looked much better before.  And now that we have bold phrases in the description, I think it looks ok...  That the reader get to see/know who are the developers is important, too.
- Put your names under "Current developers" - I think this is important.

EDIT: I happened to remove `applications.rst` and `features.rst` because I had problems getting the Contents to work. It was not really intentional to push this.

### CODE REVIEW

**Comment by mkasemer** [comment]
Per 225378f, I've made some small edits:

- minor edits to homepage descriptions
- put `applications.rst` and `features.rst` into a folder labeled `to_do` so I can work on them after 11 August
- removed hieroglyphic favicon for Neper (commented out in `conf.py`)

@rquey - if you're okay with these changes please merge, and I will then make and update `gh_pages` branch. Thanks for the edits.

**Comment by mkasemer** [comment]
@jcappola - before we merge we need working links for the pdf and the tarball. I think this requires a new folder, as well.

**Comment by jcappola** [comment]
I've added these folders to back to the source. The links _should_ work once the file is actually present.

**Comment by mkasemer** [comment]
Before merging, let's put those files in.

**Comment by jcappola** [comment]
> Before merging, let's put those files in.

I'll check out this branch and add manually per @rquey's comment.

**Comment by rquey** [comment]
@mkasemer, @jcappola, the GitHub way of doing this is to push the website to a `gh-pages` branch on the *project repo* (FEPX), not a separate repo (FEPX-website). It would probably be better if we comply to this...

The `gh-pages` branch must be a detached branch.

**Comment by mkasemer** [comment]
I'm fine with making a new gh-pages branch on the FEPX repo once we put the source up there. I will likewise edit domain forwarding for `fepx.info` at that time.

**Comment by jcappola** [comment]
Hand updated 1.0.0 doc and source tarball are now up on the branch. The linking works locally, but needs to be confirmed once its moved over to `gh-pages`. Likewise all links on the page should be confirmed as valid.

I found that making a tarball with hidden git objects is an absolute nightmare so I have cleaned all `.git` stuff from the uploaded tarball. Anyone downloading the source directly from a tarball is very likely to not be using git (otherwise they would be cloning).

**Comment by mkasemer** [comment]
New version is now live at fepx.info. We can directly port this gh-pages branch to the new FEPX repo when that's up, and I will handle forwarding then.

**Pull request merged**
